---
- hosts: all
  become: yes
  gather_facts: yes
  vars:
    jenkins_package_state: latest
    jenkins_plugins:
        - git
        - ldap
        - blueocean
    jenkins_plugins_state: latest
    #with_dependencies: yes

  tasks:
  - name: Install libselinux as prerequisite for SELinux Ansible module
    yum:
      name: "{{item}}"
      state: latest
    with_items:
      - libselinux-python
      - libsemanage-python

  - name: Disable SELinux at next reboot
    selinux:
      state: disabled

  - name: Disable IPv6 with sysctl
    sysctl: name={{ item }} value=1 state=present
    with_items:
      - net.ipv6.conf.all.disable_ipv6
      - net.ipv6.conf.default.disable_ipv6
      - net.ipv6.conf.lo.disable_ipv6

  - name: install maven (and other packages if needed)
    yum:
      name: "{{item}}"
      state: latest
    with_items:
      - maven
      - git

  roles:
    - geerlingguy.nfs
    - geerlingguy.packer-rhel
    - role: geerlingguy.java
      when: ansible_os_family == 'RedHat'
      java_packages:
        - java-1.8.0-openjdk
    - role: geerlingguy.jenkins
    - role: mamercad.grafana

